//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xeus2.Properties {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public sealed class Copy_of_Resources {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        private Copy_of_Resources() {
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("xeus2.Properties.Copy of Resources", typeof(Copy_of_Resources).Assembly);
                    _resourceManager = temp;
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to '\nThis service is already registered'.
        /// </summary>
        public static string Constant_AlreadyRegistered {
            get {
                return ResourceManager.GetString("Constant_AlreadyRegistered", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Email'.
        /// </summary>
        public static string Constant_Email {
            get {
                return ResourceManager.GetString("Constant_Email", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Enter email for Search'.
        /// </summary>
        public static string Constant_EnterEmailForSearch {
            get {
                return ResourceManager.GetString("Constant_EnterEmailForSearch", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Enter an e-mail address for this Service'.
        /// </summary>
        public static string Constant_EnterEmailForService {
            get {
                return ResourceManager.GetString("Constant_EnterEmailForService", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Enter first name for Search'.
        /// </summary>
        public static string Constant_EnterFirstNameForSearch {
            get {
                return ResourceManager.GetString("Constant_EnterFirstNameForSearch", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Enter last name for Search'.
        /// </summary>
        public static string Constant_EnterLastNameForSearch {
            get {
                return ResourceManager.GetString("Constant_EnterLastNameForSearch", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Enter you login name for this Service'.
        /// </summary>
        public static string Constant_EnterLoginNameForService {
            get {
                return ResourceManager.GetString("Constant_EnterLoginNameForService", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Enter nickname for Search'.
        /// </summary>
        public static string Constant_EnterNicknameForSearch {
            get {
                return ResourceManager.GetString("Constant_EnterNicknameForSearch", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Enter your password for this Service'.
        /// </summary>
        public static string Constant_EnterPasswordForService {
            get {
                return ResourceManager.GetString("Constant_EnterPasswordForService", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'First name'.
        /// </summary>
        public static string Constant_FirstName {
            get {
                return ResourceManager.GetString("Constant_FirstName", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'General'.
        /// </summary>
        public static string Constant_General {
            get {
                return ResourceManager.GetString("Constant_General", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Incomplete data from server'.
        /// </summary>
        public static string Constant_IncompleteData {
            get {
                return ResourceManager.GetString("Constant_IncompleteData", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'JID'.
        /// </summary>
        public static string Constant_Jid {
            get {
                return ResourceManager.GetString("Constant_Jid", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Last name'.
        /// </summary>
        public static string Constant_LastName {
            get {
                return ResourceManager.GetString("Constant_LastName", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Nickname'.
        /// </summary>
        public static string Constant_Nickname {
            get {
                return ResourceManager.GetString("Constant_Nickname", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'No Message'.
        /// </summary>
        public static string Constant_NoMessage {
            get {
                return ResourceManager.GetString("Constant_NoMessage", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Password'.
        /// </summary>
        public static string Constant_Password {
            get {
                return ResourceManager.GetString("Constant_Password", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Unknown Service'.
        /// </summary>
        public static string Constant_UnknownService {
            get {
                return ResourceManager.GetString("Constant_UnknownService", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'User Name'.
        /// </summary>
        public static string Constant_UserName {
            get {
                return ResourceManager.GetString("Constant_UserName", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error {0} - {1}'.
        /// </summary>
        public static string Error_CodeMsg {
            get {
                return ResourceManager.GetString("Error_CodeMsg", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Command result failed for &apos;{0}&apos;'.
        /// </summary>
        public static string Error_CommandResultFailed {
            get {
                return ResourceManager.GetString("Error_CommandResultFailed", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Discovery failed for &apos;{0}&apos;'.
        /// </summary>
        public static string Error_DiscoFailed {
            get {
                return ResourceManager.GetString("Error_DiscoFailed", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Invalid contact property name &apos;{0}&apos;'.
        /// </summary>
        public static string Error_InvalidContactProp {
            get {
                return ResourceManager.GetString("Error_InvalidContactProp", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'DisplayName can&apos;t be used here'.
        /// </summary>
        public static string Error_InvDisplayName {
            get {
                return ResourceManager.GetString("Error_InvDisplayName", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Room nickname request for &apos;{0}&apos; failed'.
        /// </summary>
        public static string Error_RoomNickFailed {
            get {
                return ResourceManager.GetString("Error_RoomNickFailed", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Service discovery of &apos;{0}&apos; failed - Error {1}'.
        /// </summary>
        public static string Error_ServiceDiscoFailed {
            get {
                return ResourceManager.GetString("Error_ServiceDiscoFailed", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to '&apos;{0}&apos; Service search succeeded'.
        /// </summary>
        public static string Even_SearchSucceeded {
            get {
                return ResourceManager.GetString("Even_SearchSucceeded", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Client &apos;{0}&apos; is now connected to your account &apos;{2}&apos; - priority {1}, status &apos;{2}&apos;'.
        /// </summary>
        public static string Event_AnotherClient {
            get {
                return ResourceManager.GetString("Event_AnotherClient", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to '&apos;{0}&apos; priority is higher than yours'.
        /// </summary>
        public static string Event_AnotherClientHigher {
            get {
                return ResourceManager.GetString("Event_AnotherClientHigher", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to '&apos;{0}&apos; priority is lower than yours'.
        /// </summary>
        public static string Event_AnotherClientLower {
            get {
                return ResourceManager.GetString("Event_AnotherClientLower", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Authorization failed'.
        /// </summary>
        public static string Event_AuthFailed {
            get {
                return ResourceManager.GetString("Event_AuthFailed", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Command {0} cancelled'.
        /// </summary>
        public static string Event_CommandCancelled {
            get {
                return ResourceManager.GetString("Event_CommandCancelled", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Command execution of service {0} failed'.
        /// </summary>
        public static string Event_CommandExecFailed {
            get {
                return ResourceManager.GetString("Event_CommandExecFailed", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Presence of contact &apos;{0}&apos; has changed from &apos;{1}&apos; to &apos;{2}&apos;'.
        /// </summary>
        public static string Event_PresenceChange {
            get {
                return ResourceManager.GetString("Event_PresenceChange", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Getting registration Info of Service &apos;{0}&apos;'.
        /// </summary>
        public static string Event_RegInfoFailed {
            get {
                return ResourceManager.GetString("Event_RegInfoFailed", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to '&apos;{0}&apos; Service registration failed with &apos;{1}&apos;'.
        /// </summary>
        public static string Event_RegistrationFailed {
            get {
                return ResourceManager.GetString("Event_RegistrationFailed", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to '&apos;{0}&apos; Service registration succeeded'.
        /// </summary>
        public static string Event_RegistrationSucceeded {
            get {
                return ResourceManager.GetString("Event_RegistrationSucceeded", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to '&apos;{0}&apos; Service search failed with &apos;{1}&apos;'.
        /// </summary>
        public static string Event_SearchFailed {
            get {
                return ResourceManager.GetString("Event_SearchFailed", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Getting search Info of Service &apos;{0}&apos;'.
        /// </summary>
        public static string Event_SearchInfoFailed {
            get {
                return ResourceManager.GetString("Event_SearchInfoFailed", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Presence infocoming from unknow contact &apos;{0}&apos; ({1})'.
        /// </summary>
        public static string Event_UnknownPresence {
            get {
                return ResourceManager.GetString("Event_UnknownPresence", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'MUC {0} configuration failed with &apos;{1}&apos;'.
        /// </summary>
        public static string EventError_MucConfigFailed {
            get {
                return ResourceManager.GetString("EventError_MucConfigFailed", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Unknow Status Code'.
        /// </summary>
        public static string MucStatus_000 {
            get {
                return ResourceManager.GetString("MucStatus_000", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Any occupant is allowed to see full JIDs'.
        /// </summary>
        public static string MucStatus_100 {
            get {
                return ResourceManager.GetString("MucStatus_100", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Affiliation changed while not in the room'.
        /// </summary>
        public static string MucStatus_101 {
            get {
                return ResourceManager.GetString("MucStatus_101", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Room now shows unavailable members'.
        /// </summary>
        public static string MucStatus_102 {
            get {
                return ResourceManager.GetString("MucStatus_102", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Room now does not show unavailable members'.
        /// </summary>
        public static string MucStatus_103 {
            get {
                return ResourceManager.GetString("MucStatus_103", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Non-privacy-related room configuration change has occurred'.
        /// </summary>
        public static string MucStatus_104 {
            get {
                return ResourceManager.GetString("MucStatus_104", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Presence refers to one of its own room occupants'.
        /// </summary>
        public static string MucStatus_110 {
            get {
                return ResourceManager.GetString("MucStatus_110", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Room logging is now enabled'.
        /// </summary>
        public static string MucStatus_170 {
            get {
                return ResourceManager.GetString("MucStatus_170", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Room logging is now disabled'.
        /// </summary>
        public static string MucStatus_171 {
            get {
                return ResourceManager.GetString("MucStatus_171", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'The room is now non-anonymous'.
        /// </summary>
        public static string MucStatus_172 {
            get {
                return ResourceManager.GetString("MucStatus_172", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Room is now semi-anonymous'.
        /// </summary>
        public static string MucStatus_173 {
            get {
                return ResourceManager.GetString("MucStatus_173", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Room is now fully-anonymous'.
        /// </summary>
        public static string MucStatus_174 {
            get {
                return ResourceManager.GetString("MucStatus_174", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'A new room has been created'.
        /// </summary>
        public static string MucStatus_201 {
            get {
                return ResourceManager.GetString("MucStatus_201", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Service has assigned or modified the roomnick'.
        /// </summary>
        public static string MucStatus_210 {
            get {
                return ResourceManager.GetString("MucStatus_210", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Banned from the room'.
        /// </summary>
        public static string MucStatus_301 {
            get {
                return ResourceManager.GetString("MucStatus_301", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'New room nickname'.
        /// </summary>
        public static string MucStatus_303 {
            get {
                return ResourceManager.GetString("MucStatus_303", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Kicked from the room'.
        /// </summary>
        public static string MucStatus_307 {
            get {
                return ResourceManager.GetString("MucStatus_307", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Removed from the room because of an affiliation change'.
        /// </summary>
        public static string MucStatus_321 {
            get {
                return ResourceManager.GetString("MucStatus_321", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Removed from the room because the room has been changed to members-only and the user is not a member'.
        /// </summary>
        public static string MucStatus_322 {
            get {
                return ResourceManager.GetString("MucStatus_322", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Being removed from the room because of a system shutdown'.
        /// </summary>
        public static string MucStatus_332 {
            get {
                return ResourceManager.GetString("MucStatus_332", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Moderator'.
        /// </summary>
        public static string Role_Moderator {
            get {
                return ResourceManager.GetString("Role_Moderator", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'None'.
        /// </summary>
        public static string Role_None {
            get {
                return ResourceManager.GetString("Role_None", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Participant'.
        /// </summary>
        public static string Role_Participant {
            get {
                return ResourceManager.GetString("Role_Participant", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Visitor'.
        /// </summary>
        public static string Role_Visitor {
            get {
                return ResourceManager.GetString("Role_Visitor", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Error {0} - {1}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <param name="arg1">An object (1) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string Error_CodeMsgFormat(object arg0, object arg1) {
            return string.Format(_resourceCulture, Error_CodeMsg, arg0, arg1);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Command result failed for &apos;{0}&apos;'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string Error_CommandResultFailedFormat(object arg0) {
            return string.Format(_resourceCulture, Error_CommandResultFailed, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Discovery failed for &apos;{0}&apos;'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string Error_DiscoFailedFormat(object arg0) {
            return string.Format(_resourceCulture, Error_DiscoFailed, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Invalid contact property name &apos;{0}&apos;'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string Error_InvalidContactPropFormat(object arg0) {
            return string.Format(_resourceCulture, Error_InvalidContactProp, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Room nickname request for &apos;{0}&apos; failed'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string Error_RoomNickFailedFormat(object arg0) {
            return string.Format(_resourceCulture, Error_RoomNickFailed, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Service discovery of &apos;{0}&apos; failed - Error {1}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <param name="arg1">An object (1) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string Error_ServiceDiscoFailedFormat(object arg0, object arg1) {
            return string.Format(_resourceCulture, Error_ServiceDiscoFailed, arg0, arg1);
        }
        
        /// <summary>
        /// Formats a localized string similar to '&apos;{0}&apos; Service search succeeded'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string Even_SearchSucceededFormat(object arg0) {
            return string.Format(_resourceCulture, Even_SearchSucceeded, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Client &apos;{0}&apos; is now connected to your account &apos;{2}&apos; - priority {1}, status &apos;{2}&apos;'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <param name="arg1">An object (1) to format.</param>
        /// <param name="arg2">An object (2) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string Event_AnotherClientFormat(object arg0, object arg1, object arg2) {
            return string.Format(_resourceCulture, Event_AnotherClient, arg0, arg1, arg2);
        }
        
        /// <summary>
        /// Formats a localized string similar to '&apos;{0}&apos; priority is higher than yours'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string Event_AnotherClientHigherFormat(object arg0) {
            return string.Format(_resourceCulture, Event_AnotherClientHigher, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to '&apos;{0}&apos; priority is lower than yours'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string Event_AnotherClientLowerFormat(object arg0) {
            return string.Format(_resourceCulture, Event_AnotherClientLower, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Command {0} cancelled'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string Event_CommandCancelledFormat(object arg0) {
            return string.Format(_resourceCulture, Event_CommandCancelled, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Command execution of service {0} failed'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string Event_CommandExecFailedFormat(object arg0) {
            return string.Format(_resourceCulture, Event_CommandExecFailed, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Presence of contact &apos;{0}&apos; has changed from &apos;{1}&apos; to &apos;{2}&apos;'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <param name="arg1">An object (1) to format.</param>
        /// <param name="arg2">An object (2) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string Event_PresenceChangeFormat(object arg0, object arg1, object arg2) {
            return string.Format(_resourceCulture, Event_PresenceChange, arg0, arg1, arg2);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Getting registration Info of Service &apos;{0}&apos;'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string Event_RegInfoFailedFormat(object arg0) {
            return string.Format(_resourceCulture, Event_RegInfoFailed, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to '&apos;{0}&apos; Service registration failed with &apos;{1}&apos;'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <param name="arg1">An object (1) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string Event_RegistrationFailedFormat(object arg0, object arg1) {
            return string.Format(_resourceCulture, Event_RegistrationFailed, arg0, arg1);
        }
        
        /// <summary>
        /// Formats a localized string similar to '&apos;{0}&apos; Service registration succeeded'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string Event_RegistrationSucceededFormat(object arg0) {
            return string.Format(_resourceCulture, Event_RegistrationSucceeded, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to '&apos;{0}&apos; Service search failed with &apos;{1}&apos;'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <param name="arg1">An object (1) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string Event_SearchFailedFormat(object arg0, object arg1) {
            return string.Format(_resourceCulture, Event_SearchFailed, arg0, arg1);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Getting search Info of Service &apos;{0}&apos;'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string Event_SearchInfoFailedFormat(object arg0) {
            return string.Format(_resourceCulture, Event_SearchInfoFailed, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Presence infocoming from unknow contact &apos;{0}&apos; ({1})'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <param name="arg1">An object (1) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string Event_UnknownPresenceFormat(object arg0, object arg1) {
            return string.Format(_resourceCulture, Event_UnknownPresence, arg0, arg1);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'MUC {0} configuration failed with &apos;{1}&apos;'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <param name="arg1">An object (1) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string EventError_MucConfigFailedFormat(object arg0, object arg1) {
            return string.Format(_resourceCulture, EventError_MucConfigFailed, arg0, arg1);
        }
    }
}
