//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xeus2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("xeus2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Constant_Email {
            get {
                return ResourceManager.GetString("Constant_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter email for Search.
        /// </summary>
        internal static string Constant_EnterEmailForSearch {
            get {
                return ResourceManager.GetString("Constant_EnterEmailForSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an e-mail address for this Service.
        /// </summary>
        internal static string Constant_EnterEmailForService {
            get {
                return ResourceManager.GetString("Constant_EnterEmailForService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter first name for Search.
        /// </summary>
        internal static string Constant_EnterFirstNameForSearch {
            get {
                return ResourceManager.GetString("Constant_EnterFirstNameForSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter last name for Search.
        /// </summary>
        internal static string Constant_EnterLastNameForSearch {
            get {
                return ResourceManager.GetString("Constant_EnterLastNameForSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter you login name for this Service.
        /// </summary>
        internal static string Constant_EnterLoginNameForService {
            get {
                return ResourceManager.GetString("Constant_EnterLoginNameForService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter nickname for Search.
        /// </summary>
        internal static string Constant_EnterNicknameForSearch {
            get {
                return ResourceManager.GetString("Constant_EnterNicknameForSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password for this Service.
        /// </summary>
        internal static string Constant_EnterPasswordForService {
            get {
                return ResourceManager.GetString("Constant_EnterPasswordForService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string Constant_FirstName {
            get {
                return ResourceManager.GetString("Constant_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string Constant_General {
            get {
                return ResourceManager.GetString("Constant_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string Constant_LastName {
            get {
                return ResourceManager.GetString("Constant_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        internal static string Constant_Nickname {
            get {
                return ResourceManager.GetString("Constant_Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Constant_Password {
            get {
                return ResourceManager.GetString("Constant_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Service.
        /// </summary>
        internal static string Constant_UnknownService {
            get {
                return ResourceManager.GetString("Constant_UnknownService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string Constant_UserName {
            get {
                return ResourceManager.GetString("Constant_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0} - {1}.
        /// </summary>
        internal static string Error_CodeMsg {
            get {
                return ResourceManager.GetString("Error_CodeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid contact property name &apos;{0}&apos;.
        /// </summary>
        internal static string Error_InvalidContactProp {
            get {
                return ResourceManager.GetString("Error_InvalidContactProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayName can&apos;t be used here.
        /// </summary>
        internal static string Error_InvDisplayName {
            get {
                return ResourceManager.GetString("Error_InvDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service discovery of &apos;{0}&apos; failed - Error {1}.
        /// </summary>
        internal static string Error_ServiceDiscoFailed {
            get {
                return ResourceManager.GetString("Error_ServiceDiscoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; Service search succeeded.
        /// </summary>
        internal static string Even_SearchSucceeded {
            get {
                return ResourceManager.GetString("Even_SearchSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client &apos;{0}&apos; is now connected to your account &apos;{2}&apos; - priority {1}, status &apos;{2}&apos;.
        /// </summary>
        internal static string Event_AnotherClient {
            get {
                return ResourceManager.GetString("Event_AnotherClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; priority is higher than yours.
        /// </summary>
        internal static string Event_AnotherClientHigher {
            get {
                return ResourceManager.GetString("Event_AnotherClientHigher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; priority is lower than yours.
        /// </summary>
        internal static string Event_AnotherClientLower {
            get {
                return ResourceManager.GetString("Event_AnotherClientLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization failed.
        /// </summary>
        internal static string Event_AuthFailed {
            get {
                return ResourceManager.GetString("Event_AuthFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presence of contact &apos;{0}&apos; has changed from &apos;{1}&apos; to &apos;{2}&apos;.
        /// </summary>
        internal static string Event_PresenceChange {
            get {
                return ResourceManager.GetString("Event_PresenceChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting registration Info of Service &apos;{0}&apos;.
        /// </summary>
        internal static string Event_RegInfoFailed {
            get {
                return ResourceManager.GetString("Event_RegInfoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; Service registration failed with &apos;{1}&apos;.
        /// </summary>
        internal static string Event_RegistrationFailed {
            get {
                return ResourceManager.GetString("Event_RegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; Service registration succeeded.
        /// </summary>
        internal static string Event_RegistrationSucceeded {
            get {
                return ResourceManager.GetString("Event_RegistrationSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; Service search failed with &apos;{1}&apos;.
        /// </summary>
        internal static string Event_SearchFailed {
            get {
                return ResourceManager.GetString("Event_SearchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting search Info of Service &apos;{0}&apos;.
        /// </summary>
        internal static string Event_SearchInfoFailed {
            get {
                return ResourceManager.GetString("Event_SearchInfoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presence infocoming from unknow contact &apos;{0}&apos; ({1}).
        /// </summary>
        internal static string Event_UnknownPresence {
            get {
                return ResourceManager.GetString("Event_UnknownPresence", resourceCulture);
            }
        }
    }
}
